/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.ListaEnlazada;
import Clases.Proceso;

/**
 *
 * @author adria
 */
public class Form_P1T4 extends javax.swing.JFrame {

    /**
     * Creates new form Form_P1T4
     */
    
    
    ListaEnlazada objLisEn;
    
    Proceso objProc;
    public Form_P1T4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jBut_Crear = new javax.swing.JButton();
        jBut_Aleatorio = new javax.swing.JButton();
        jBut_InsAlIni = new javax.swing.JButton();
        jBut_InsAlFin = new javax.swing.JButton();
        jBut_ElimAlIni = new javax.swing.JButton();
        jBut_ElimAlFin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Aleatorio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ListaEnlazada = new javax.swing.JTable();
        jBut_InvertirLista = new javax.swing.JButton();
        jBut_EliminarMedio = new javax.swing.JButton();
        jButt_ELIMSEG_ELIMPEN = new javax.swing.JButton();
        jBut_IntPos1XIntPos2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jText_Pos1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jText_Pos2 = new javax.swing.JTextField();
        jButt_EliminarPosPares = new javax.swing.JButton();
        jButt_IntPosParXIntPosImp = new javax.swing.JButton();
        jBut_EliminarElem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBut_Crear.setText("CREAR");
        jBut_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CrearActionPerformed(evt);
            }
        });

        jBut_Aleatorio.setText("ALEATORIO");
        jBut_Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_AleatorioActionPerformed(evt);
            }
        });

        jBut_InsAlIni.setText("INSERTAR INICIO");
        jBut_InsAlIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InsAlIniActionPerformed(evt);
            }
        });

        jBut_InsAlFin.setText("INSERTAR FINAL");
        jBut_InsAlFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InsAlFinActionPerformed(evt);
            }
        });

        jBut_ElimAlIni.setText("ELIMINAR INICIO");
        jBut_ElimAlIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ElimAlIniActionPerformed(evt);
            }
        });

        jBut_ElimAlFin.setText("ELIMINAR FINAL");
        jBut_ElimAlFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ElimAlFinActionPerformed(evt);
            }
        });

        jTable_Aleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ));
        jScrollPane1.setViewportView(jTable_Aleatorio);

        jTable_ListaEnlazada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_ListaEnlazada);

        jBut_InvertirLista.setText("INVERTIR LISTA");
        jBut_InvertirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InvertirListaActionPerformed(evt);
            }
        });

        jBut_EliminarMedio.setText("ELIMINAR MEDIO");
        jBut_EliminarMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EliminarMedioActionPerformed(evt);
            }
        });

        jButt_ELIMSEG_ELIMPEN.setText("ELIMSEG_ELIMPEN");
        jButt_ELIMSEG_ELIMPEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_ELIMSEG_ELIMPENActionPerformed(evt);
            }
        });

        jBut_IntPos1XIntPos2.setText("INTPOS1_X_INTPOS2");
        jBut_IntPos1XIntPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_IntPos1XIntPos2ActionPerformed(evt);
            }
        });

        jLabel1.setText("POS1");

        jText_Pos1.setFocusable(false);
        jText_Pos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Pos1ActionPerformed(evt);
            }
        });

        jLabel2.setText("POS2");

        jText_Pos2.setFocusable(false);
        jText_Pos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Pos2ActionPerformed(evt);
            }
        });

        jButt_EliminarPosPares.setText("ELIMINAR POS PARES");
        jButt_EliminarPosPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_EliminarPosParesActionPerformed(evt);
            }
        });

        jButt_IntPosParXIntPosImp.setText("INTPOSXPOSPAR");
        jButt_IntPosParXIntPosImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_IntPosParXIntPosImpActionPerformed(evt);
            }
        });

        jBut_EliminarElem.setText("INTERCAMBIAR ELEM");
        jBut_EliminarElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EliminarElemActionPerformed(evt);
            }
        });

        jButton2.setText("ELIMINAR POS 3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut_Crear)
                                .addGap(18, 18, 18)
                                .addComponent(jBut_Aleatorio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jText_Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jText_Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut_IntPos1XIntPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut_InsAlIni)
                                .addGap(18, 18, 18)
                                .addComponent(jBut_ElimAlIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBut_InvertirLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBut_InsAlFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButt_ELIMSEG_ELIMPEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBut_ElimAlFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButt_IntPosParXIntPosImp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBut_EliminarElem)
                            .addComponent(jButt_EliminarPosPares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBut_EliminarMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_Crear)
                    .addComponent(jBut_Aleatorio)
                    .addComponent(jBut_InsAlIni)
                    .addComponent(jBut_ElimAlIni))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jText_Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBut_ElimAlFin))
                            .addComponent(jBut_InsAlFin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jText_Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBut_InvertirLista)
                            .addComponent(jButt_ELIMSEG_ELIMPEN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBut_IntPos1XIntPos2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBut_EliminarMedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButt_EliminarPosPares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBut_EliminarElem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButt_IntPosParXIntPosImp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CrearActionPerformed
      
        objLisEn=new ListaEnlazada();
    }//GEN-LAST:event_jBut_CrearActionPerformed

    private void jBut_AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_AleatorioActionPerformed
      
        objProc=new Proceso();
        
        
        objProc.Aleatorio(jTable_Aleatorio);
    }//GEN-LAST:event_jBut_AleatorioActionPerformed

    private void jBut_InsAlIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InsAlIniActionPerformed
        // TODO add your handling code here:
        
        int numProc=Integer.parseInt(this.jTable_Aleatorio.getValueAt(0, 0).toString());
        String tipoProc=this.jTable_Aleatorio.getValueAt(0, 1).toString();
        double quantum = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0, 2).toString());
        
   
        objProc=new Proceso(numProc, tipoProc, quantum);
        
        
        objLisEn.insAlIni(objProc);
        
        
        objLisEn.mostrarLista(jTable_ListaEnlazada );
    }//GEN-LAST:event_jBut_InsAlIniActionPerformed

    private void jBut_ElimAlIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ElimAlIniActionPerformed
        // TODO add your handling code here:
        
        objLisEn.elimAlIni();
  
       objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_ElimAlIniActionPerformed

    private void jBut_InsAlFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InsAlFinActionPerformed
        // TODO add your handling code here:
        
         int numProc=Integer.parseInt(this.jTable_Aleatorio.getValueAt(0, 0).toString());
        String tipoProc=this.jTable_Aleatorio.getValueAt(0, 1).toString();
        double quantum = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0, 2).toString());
        
      
        objProc=new Proceso(numProc, tipoProc, quantum);
       
        objLisEn.insAlFin(objProc);
        
        objLisEn.mostrarLista(jTable_ListaEnlazada );
    }//GEN-LAST:event_jBut_InsAlFinActionPerformed

    private void jBut_ElimAlFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ElimAlFinActionPerformed
        // TODO add your handling code here:
       
        objLisEn.elimAlFin();
        
             objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_ElimAlFinActionPerformed

    private void jBut_InvertirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InvertirListaActionPerformed
        // TODO add your handling code here:
        objLisEn.inveList();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_InvertirListaActionPerformed

    private void jBut_EliminarMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EliminarMedioActionPerformed
        // TODO add your handling code here:
        objLisEn.eliminarMedio();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_EliminarMedioActionPerformed

    private void jButt_ELIMSEG_ELIMPENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_ELIMSEG_ELIMPENActionPerformed
        // TODO add your handling code here:
        objLisEn.ElimSegElimPen();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jButt_ELIMSEG_ELIMPENActionPerformed

    private void jText_Pos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Pos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Pos1ActionPerformed

    private void jText_Pos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Pos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Pos2ActionPerformed

    private void jBut_IntPos1XIntPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_IntPos1XIntPos2ActionPerformed
        // TODO add your handling code here:
        //Variable pos1 y pos2 para guardar las posiciones
        int pos1, pos2;
        pos1= Integer.parseInt(this.jText_Pos1.getText());
        pos2= Integer.parseInt(this.jText_Pos2.getText());
        
        objLisEn.intElemP1XElemP2(pos1, pos2);
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_IntPos1XIntPos2ActionPerformed

    private void jButt_EliminarPosParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_EliminarPosParesActionPerformed
        // TODO add your handling code here:
        objLisEn.elimPosPares();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jButt_EliminarPosParesActionPerformed

    private void jButt_IntPosParXIntPosImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_IntPosParXIntPosImpActionPerformed
        // TODO add your handling code here:
        objLisEn.intPosImpPosPar();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jButt_IntPosParXIntPosImpActionPerformed

    private void jBut_EliminarElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EliminarElemActionPerformed
        // TODO add your handling code here:
        int pos = Integer.parseInt(this.jText_Pos1.getText());
        int numProc = Integer.parseInt(this.jTable_Aleatorio.getValueAt(0, 0).toString());
        String tipoProc = this.jTable_Aleatorio.getValueAt(0, 1).toString();
        double quantum = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0, 2).toString());
  
        objLisEn.remplazarElemento(objProc, pos);
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jBut_EliminarElemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        objLisEn.ElimPosMul3();
        objLisEn.mostrarLista(jTable_ListaEnlazada);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_P1T4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_P1T4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_P1T4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_P1T4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_P1T4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Aleatorio;
    private javax.swing.JButton jBut_Crear;
    private javax.swing.JButton jBut_ElimAlFin;
    private javax.swing.JButton jBut_ElimAlIni;
    private javax.swing.JButton jBut_EliminarElem;
    private javax.swing.JButton jBut_EliminarMedio;
    private javax.swing.JButton jBut_InsAlFin;
    private javax.swing.JButton jBut_InsAlIni;
    private javax.swing.JButton jBut_IntPos1XIntPos2;
    private javax.swing.JButton jBut_InvertirLista;
    private javax.swing.JButton jButt_ELIMSEG_ELIMPEN;
    private javax.swing.JButton jButt_EliminarPosPares;
    private javax.swing.JButton jButt_IntPosParXIntPosImp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Aleatorio;
    private javax.swing.JTable jTable_ListaEnlazada;
    private javax.swing.JTextField jText_Pos1;
    private javax.swing.JTextField jText_Pos2;
    // End of variables declaration//GEN-END:variables
}
