/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.Proceso;
import Clases.SistemaOperativo;

/**
 *
 * @author aa422
 */
public class Form_P2T1 extends javax.swing.JFrame {

    Proceso objP = new Proceso();
    SistemaOperativo objSO = new SistemaOperativo();
    /**
     * Creates new form Form_P2T1
     */
    
    
    public Form_P2T1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBut_Aleatorio = new javax.swing.JButton();
        jBut_Guardar = new javax.swing.JButton();
        jBut_Mostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_Proceso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_Tipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_TiempoLlegada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_TiempoEjecucion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_Prioridad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_Quantum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jCB_Proceso = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBut_Buscar = new javax.swing.JButton();
        jBut_Modificar = new javax.swing.JButton();
        jBut_Eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JCB_Quantum = new javax.swing.JComboBox<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBut_Aleatorio.setText("Aleatorio");
        jBut_Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_AleatorioActionPerformed(evt);
            }
        });

        jBut_Guardar.setText("Guardar");
        jBut_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_GuardarActionPerformed(evt);
            }
        });

        jBut_Mostrar.setText("Mostrar");
        jBut_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MostrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Proceso:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("T.Llegada:");

        jLabel4.setText("T.Ejecucion:");

        jLabel5.setText("Prioridad:");

        jLabel6.setText("Quantum:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Tipo", "T.llegada", "T.Ejecucion", "Prioridad", "Quantum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Proceso:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Tipo", "T.llegada", "T.Ejecucion", "Prioridad", "Quantum"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jBut_Buscar.setText("Buscar");
        jBut_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_BuscarActionPerformed(evt);
            }
        });

        jBut_Modificar.setText("Modificar");
        jBut_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ModificarActionPerformed(evt);
            }
        });

        jBut_Eliminar.setText("Eliminar");
        jBut_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantum");

        JCB_Quantum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        JCB_Quantum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB_QuantumItemStateChanged(evt);
            }
        });
        JCB_Quantum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_QuantumActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBut_Aleatorio)
                        .addGap(33, 33, 33)
                        .addComponent(jBut_Guardar)
                        .addGap(36, 36, 36)
                        .addComponent(jBut_Mostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_TiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_TiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut_Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut_Modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut_Eliminar)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBut_Aleatorio)
                            .addComponent(jBut_Guardar)
                            .addComponent(jBut_Mostrar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTF_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTF_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTF_TiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTF_TiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTF_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jCB_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBut_Buscar)
                            .addComponent(jBut_Modificar)
                            .addComponent(jBut_Eliminar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTF_Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JCB_Quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_AleatorioActionPerformed
        // TODO add your handling code here:
        objP.aleatorio(jTF_Proceso, jTF_Tipo, jTF_TiempoLlegada, jTF_TiempoEjecucion, jTF_Prioridad, jTF_Quantum);
    }//GEN-LAST:event_jBut_AleatorioActionPerformed

    private void jBut_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_GuardarActionPerformed
        // TODO add your handling code here:
        objP = new Proceso(this.jTF_Proceso.getText(), this.jTF_Tipo.getText(),
        Double.parseDouble(this.jTF_TiempoLlegada.getText()), 
        Double.parseDouble(this.jTF_TiempoEjecucion.getText()),
        Integer.parseInt(this.jTF_Prioridad.getText()),
        Integer.parseInt(this.jTF_Quantum.getText()));
        
        objSO.Guardar(objP);
        this.jCB_Proceso.addItem(this.jTF_Proceso.getText());
    }//GEN-LAST:event_jBut_GuardarActionPerformed

    private void jBut_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MostrarActionPerformed
        // TODO add your handling code here:
        objSO.Mostrar(jTable1);
    }//GEN-LAST:event_jBut_MostrarActionPerformed

    private void jBut_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_BuscarActionPerformed
        // TODO add your handling code here:
        objSO.Buscar(jCB_Proceso, jTable2);
    }//GEN-LAST:event_jBut_BuscarActionPerformed

    private void jBut_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ModificarActionPerformed
        // TODO add your handling code here:
        objSO.Modificar(jCB_Proceso, jTable2);
        objSO.Mostrar(jTable1);
    }//GEN-LAST:event_jBut_ModificarActionPerformed

    private void jBut_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EliminarActionPerformed
        // TODO add your handling code here:
        objSO.Eliminar(jCB_Proceso);
        objSO.Mostrar(jTable1);
        this.jCB_Proceso.removeItemAt(this.jCB_Proceso.getSelectedIndex());
    }//GEN-LAST:event_jBut_EliminarActionPerformed

    private void JCB_QuantumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_QuantumItemStateChanged
        // TODO add your handling code here:
        objSO.buscarQuantum(jList1, this.JCB_Quantum);
    }//GEN-LAST:event_JCB_QuantumItemStateChanged

    private void JCB_QuantumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_QuantumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_QuantumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_P2T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_P2T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_P2T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_P2T1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_P2T1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_Quantum;
    private javax.swing.JButton jBut_Aleatorio;
    private javax.swing.JButton jBut_Buscar;
    private javax.swing.JButton jBut_Eliminar;
    private javax.swing.JButton jBut_Guardar;
    private javax.swing.JButton jBut_Modificar;
    private javax.swing.JButton jBut_Mostrar;
    private javax.swing.JComboBox<String> jCB_Proceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF_Prioridad;
    private javax.swing.JTextField jTF_Proceso;
    private javax.swing.JTextField jTF_Quantum;
    private javax.swing.JTextField jTF_TiempoEjecucion;
    private javax.swing.JTextField jTF_TiempoLlegada;
    private javax.swing.JTextField jTF_Tipo;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
