/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Arbol;
import Clases.ArbolNodo;
import Clases.ArbolProceso;
import Clases.Ordenamientos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 *
 * @author adria
 */
public class Form_Arboles extends javax.swing.JFrame {
Arbol objArbol;
ArbolProceso objProc=new ArbolProceso();
Ordenamientos objOrden;
Form_Menu principal;


    /**
     * Creates new form Form_Arboles
     */
    public Form_Arboles(Form_Menu A) {
        initComponents();
        principal = A;
    }
    
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_aleatorios = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jBut_Graficar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NumProceso = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Inorden = new javax.swing.JButton();
        jButton_Postorden = new javax.swing.JButton();
        jButton_Preorden = new javax.swing.JButton();
        jButton_Insertar = new javax.swing.JButton();
        jButton_crear = new javax.swing.JButton();
        jButton_aleatorios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Arboles = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Aleatorio = new javax.swing.JTable();
        JBUT_Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable_aleatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Numero Proceso", "Tipo Proceso", "Quantum"
            }
        ));
        jScrollPane1.setViewportView(jTable_aleatorios);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBut_Graficar.setText("Graficar Arbol");
        jBut_Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_GraficarActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Num. Proceso:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(jTextField_NumProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jButton_Inorden.setText("Inorden");
        jButton_Inorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InordenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Inorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jButton_Postorden.setText("Postorden");
        jButton_Postorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PostordenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Postorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jButton_Preorden.setText("Preorden");
        jButton_Preorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PreordenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Preorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jButton_Insertar.setText("Insertar");
        jButton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jButton_crear.setText("Crear");
        jButton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jButton_aleatorios.setText("Aleatorios");
        jButton_aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aleatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_aleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jTable_Arboles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Proceso", "Tipo Proceso", "Quantum"
            }
        ));
        jScrollPane3.setViewportView(jTable_Arboles);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 240));

        jTable_Aleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Numero Proceso", "Tipo Proceso", "Quantum"
            }
        ));
        jScrollPane2.setViewportView(jTable_Aleatorio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 60));

        JBUT_Regresar.setText("Regresar");
        JBUT_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Fondo_Arbol.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertarActionPerformed
        int numProc=Integer.parseInt(this.jTable_Aleatorio.getValueAt(0,0).toString());
        String tipoProc=this.jTable_Aleatorio.getValueAt(0,1).toString();
        double quantum=Double.parseDouble(this.jTable_Aleatorio.getValueAt(0,2).toString());
        objProc=new ArbolProceso(numProc,tipoProc,quantum);
        objArbol.insertar(objProc);
    }//GEN-LAST:event_jButton_InsertarActionPerformed

    private void jButton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearActionPerformed
        objArbol=new Arbol();
    }//GEN-LAST:event_jButton_crearActionPerformed

    private void jButton_aleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aleatoriosActionPerformed
        objProc.Aleatorio(this.jTable_Aleatorio);
    }//GEN-LAST:event_jButton_aleatoriosActionPerformed

    private void jButton_InordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InordenActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.jTable_Arboles.getModel();
        modelo.setRowCount(0);
        objArbol.inorden( objArbol.getRaiz(), modelo );
    }//GEN-LAST:event_jButton_InordenActionPerformed

    private void jButton_PostordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PostordenActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.jTable_Arboles.getModel();
        modelo.setRowCount(0);
        objArbol.Posorden(objArbol.getRaiz(), modelo );
    }//GEN-LAST:event_jButton_PostordenActionPerformed

    private void jButton_PreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PreordenActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)this.jTable_Arboles.getModel();
        modelo.setRowCount(0);

        objArbol.preorden( objArbol.getRaiz(), modelo );
    }//GEN-LAST:event_jButton_PreordenActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        int NumProceso = Integer.parseInt(this.jTextField_NumProceso.getText());
        ArbolNodo []nodoEnc = new ArbolNodo[1];
        if(objArbol.BuscarNodo(NumProceso, nodoEnc))
        objArbol.eliminar(nodoEnc);
        else
        JOptionPane.showMessageDialog(null,"El nodo no se encuentra en el arbol :(");
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        int NumProceso = Integer.parseInt(this.jTextField_NumProceso.getText());
        ArbolNodo []nodoEnc = new ArbolNodo[1];
        if(objArbol.BuscarNodo(NumProceso, nodoEnc)){
            JOptionPane.showMessageDialog(null,"Se encontro el nodo :)");
        }
        else{
            JOptionPane.showMessageDialog(null, "No se ha encontrado el nodo :( ");
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jBut_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_GraficarActionPerformed
        // TODO add your handling code here:
        Form_ArbolGraficacion FormArbolG = new Form_ArbolGraficacion(this);
        FormArbolG.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBut_GraficarActionPerformed

    private void JBUT_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_JBUT_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Arboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_Regresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBut_Graficar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Inorden;
    private javax.swing.JButton jButton_Insertar;
    private javax.swing.JButton jButton_Postorden;
    private javax.swing.JButton jButton_Preorden;
    private javax.swing.JButton jButton_aleatorios;
    private javax.swing.JButton jButton_crear;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Aleatorio;
    private javax.swing.JTable jTable_Arboles;
    private javax.swing.JTable jTable_aleatorios;
    private javax.swing.JTextField jTextField_NumProceso;
    // End of variables declaration//GEN-END:variables
}
