/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Automovil;
import Clases.Proyecto_Cola;

/**
 *
 * @author adria
 */
public class Form_Cola extends javax.swing.JFrame {
    Proyecto_Cola objCola;
    Automovil objAutomovil;

    /**
     * Creates new form Form_Cola
     */
    Form_Menu principal;
    public Form_Cola(Form_Menu p) {
        initComponents();
        this.setLocationRelativeTo(null);
        principal=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBUT_ElimInsertar = new javax.swing.JButton();
        JBUT_ParImpar = new javax.swing.JButton();
        JBUT_Regresar = new javax.swing.JButton();
        JTF_Dimension = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBUT_Aleatorios = new javax.swing.JButton();
        jBUT_Insertar = new javax.swing.JButton();
        jBUt_Eliminar = new javax.swing.JButton();
        jBUT_Crear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Aleatorio = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Colas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBUT_ElimInsertar.setText("ElimInser");
        JBUT_ElimInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ElimInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_ElimInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, 30));

        JBUT_ParImpar.setText("ParImpar");
        JBUT_ParImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ParImparActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_ParImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 30));

        JBUT_Regresar.setText("Regresar");
        JBUT_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        JTF_Dimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_DimensionActionPerformed(evt);
            }
        });
        getContentPane().add(JTF_Dimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Dimension");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jBUT_Aleatorios.setText("Aleatorio");
        jBUT_Aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_AleatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jBUT_Aleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 30));

        jBUT_Insertar.setText("Insertar");
        jBUT_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(jBUT_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 30));

        jBUt_Eliminar.setText("Eliminar");
        jBUt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUt_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBUt_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, 30));

        jBUT_Crear.setText("Crear");
        jBUT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_CrearActionPerformed(evt);
            }
        });
        getContentPane().add(jBUT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 30));

        jTable_Aleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "color", "Precio"
            }
        ));
        jScrollPane3.setViewportView(jTable_Aleatorio);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 100, 460, 50));

        jTable_Colas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Colas.setTableHeader(null);
        jScrollPane4.setViewportView(jTable_Colas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 160, 460, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/FondoCola.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, 471));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUT_AleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_AleatoriosActionPerformed
        // TODO add your handling code here:
        objAutomovil = new Automovil();
        objAutomovil.aleatorio(jTable_Aleatorio);

    }//GEN-LAST:event_jBUT_AleatoriosActionPerformed

    private void jBUT_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_InsertarActionPerformed
        // TODO add your handling code here:
       String placa = this.jTable_Aleatorio.getValueAt(0, 0).toString();
        String marca = this.jTable_Aleatorio.getValueAt(0, 1).toString();
        int modelo = Integer.parseInt(this.jTable_Aleatorio.getValueAt(0,2).toString());
        String color = this.jTable_Aleatorio.getValueAt(0, 3).toString();
        double precio = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0, 4).toString());
        
        objAutomovil = new Automovil(placa,marca,modelo,color,precio);
        objCola.Insertar(objAutomovil);
        objCola.Mostrar(jTable_Colas);
    }//GEN-LAST:event_jBUT_InsertarActionPerformed

    private void jBUt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUt_EliminarActionPerformed
        // TODO add your handling code here:
        objCola.Eliminar();
        objCola.Mostrar(jTable_Colas);
    }//GEN-LAST:event_jBUt_EliminarActionPerformed

    private void jBUT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_CrearActionPerformed
        // TODO add your handling code here:
        objCola = new Proyecto_Cola(Integer.parseInt(this.JTF_Dimension.getText()));
    }//GEN-LAST:event_jBUT_CrearActionPerformed

    private void JTF_DimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_DimensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_DimensionActionPerformed

    private void JBUT_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_JBUT_RegresarActionPerformed

    private void JBUT_ParImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ParImparActionPerformed
        // TODO add your handling code here:
        objCola.ParxImpar();
        objCola.Mostrar(jTable_Colas);
    }//GEN-LAST:event_JBUT_ParImparActionPerformed

    private void JBUT_ElimInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ElimInsertarActionPerformed
        // TODO add your handling code here:
        objCola.ElimSegPosicion();
        objCola.Mostrar(jTable_Colas);
    }//GEN-LAST:event_JBUT_ElimInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_ElimInsertar;
    private javax.swing.JButton JBUT_ParImpar;
    private javax.swing.JButton JBUT_Regresar;
    public static javax.swing.JTextField JTF_Dimension;
    private javax.swing.JButton jBUT_Aleatorios;
    private javax.swing.JButton jBUT_Crear;
    private javax.swing.JButton jBUT_Insertar;
    private javax.swing.JButton jBUt_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Aleatorio;
    public static javax.swing.JTable jTable_Colas;
    // End of variables declaration//GEN-END:variables
}
