/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Arbol;
import Clases.ArbolProceso;
import Clases.ArbolSimuladorBinario;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class Form_ArbolGraficacion extends javax.swing.JFrame {
Arbol objArbol;
ArbolProceso objProc=new ArbolProceso();
private ArbolSimuladorBinario Simulador = new ArbolSimuladorBinario();
Form_Arboles principal;
    /**
     * Creates new form Form_ArbolGraficacion
     */
    public Form_ArbolGraficacion(Form_Arboles A) {
        initComponents();
        this.setLocationRelativeTo(null);
        principal = A;
    }
     private void inicializar(boolean enable) {
        this.Jbut_InOrden.setEnabled(enable);
        this.JBut_PostOrden.setEnabled(enable);
        this.Jbut_PreOrden.setEnabled(enable);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBUT_Regresar = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        JPanelArbol = new javax.swing.JInternalFrame();
        JBut_PostOrden = new javax.swing.JButton();
        jText_Dibujo = new javax.swing.JTextField();
        Jbut_InOrden = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();
        JBut_Insertar = new javax.swing.JButton();
        Jbut_PreOrden = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBUT_Regresar.setText("Regresar");
        JBUT_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        JPanelArbol.setIconifiable(true);
        JPanelArbol.setMaximizable(true);
        JPanelArbol.setResizable(true);
        JPanelArbol.setEnabled(false);
        JPanelArbol.setFocusCycleRoot(false);
        JPanelArbol.setVisible(true);

        javax.swing.GroupLayout JPanelArbolLayout = new javax.swing.GroupLayout(JPanelArbol.getContentPane());
        JPanelArbol.getContentPane().setLayout(JPanelArbolLayout);
        JPanelArbolLayout.setHorizontalGroup(
            JPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        JPanelArbolLayout.setVerticalGroup(
            JPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelArbol)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelArbol)
        );
        jDesktopPane.setLayer(JPanelArbol, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 390, 250));

        JBut_PostOrden.setText("PostOrden");
        JBut_PostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBut_PostOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(JBut_PostOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(jText_Dibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 100, -1));

        Jbut_InOrden.setText("InOrden");
        Jbut_InOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbut_InOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(Jbut_InOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Arbol Grafico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserta el numero para tu arbol:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jScrollPane3.setOpaque(false);

        Resultados.setEditable(false);
        Resultados.setColumns(20);
        Resultados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Resultados.setRows(5);
        Resultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de operaciones"));
        Resultados.setOpaque(false);
        jScrollPane3.setViewportView(Resultados);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 390, 70));

        JBut_Insertar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JBut_Insertar.setText("Insertar");
        JBut_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBut_InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(JBut_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        Jbut_PreOrden.setText("PreOrden");
        Jbut_PreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbut_PreOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(Jbut_PreOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Fondo_ArbolGrafica.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 482));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBut_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBut_InsertarActionPerformed
        try {
            int dato = Integer.parseInt(jText_Dibujo.getText());
            if (this.Simulador.insertar(dato)) {
                JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                this.inicializar(true);

                complementos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);

        }
    }//GEN-LAST:event_JBut_InsertarActionPerformed

    private void Jbut_InOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbut_InOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.Simulador.inOrden();

        this.Resultados.setText("");
        this.Resultados.setText(recorrido);
    }//GEN-LAST:event_Jbut_InOrdenActionPerformed

    private void Jbut_PreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbut_PreOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.Simulador.preOrden();

        this.Resultados.setText("");
        this.Resultados.setText(recorrido);
    }//GEN-LAST:event_Jbut_PreOrdenActionPerformed

    private void JBut_PostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBut_PostOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.Simulador.postOrden();

        this.Resultados.setText("");
        this.Resultados.setText(recorrido);
    }//GEN-LAST:event_JBut_PostOrdenActionPerformed

    private void JBUT_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_JBUT_RegresarActionPerformed
    public void complementos(){
        this.repintarArbol();
    }
    private void repintarArbol() {
        this.jDesktopPane.removeAll();
        Rectangle tamaño = this.JPanelArbol.getBounds();
        this.JPanelArbol = null;
        this.JPanelArbol = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane.add(this.JPanelArbol, JLayeredPane.DEFAULT_LAYER);
        this.JPanelArbol.setVisible(true);
        this.JPanelArbol.setBounds(tamaño);
        this.JPanelArbol.setEnabled(false);
        this.JPanelArbol.add(this.Simulador.getDibujo(), BorderLayout.CENTER);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ArbolGraficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ArbolGraficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ArbolGraficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ArbolGraficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_Regresar;
    private javax.swing.JButton JBut_Insertar;
    private javax.swing.JButton JBut_PostOrden;
    private javax.swing.JInternalFrame JPanelArbol;
    private javax.swing.JButton Jbut_InOrden;
    private javax.swing.JButton Jbut_PreOrden;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jText_Dibujo;
    // End of variables declaration//GEN-END:variables
}
