/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Clases.Ordenamientos;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class Form_BusquedaOrdenacion extends javax.swing.JFrame {
    Ordenamientos OPrincipal = null;
    Form_Menu principal;
    JFileChooser Seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream Salida;

    /**
     * Creates new form Form_BusquedaOrdenacion
     */
    public Form_BusquedaOrdenacion(Form_Menu p) {
        initComponents();
        principal = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextTamaño = new javax.swing.JTextField();
        jBut_Ingresar = new javax.swing.JButton();
        jBut_Limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDatos = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jBut_Merge = new javax.swing.JButton();
        jBut_Inserccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Inserccion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Merge = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jBUt_Secuencial = new javax.swing.JButton();
        jBut_BInaria = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Binaria = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_secuencia = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jBUt_eregresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Ingrese el Tamaño del vector:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));
        getContentPane().add(jTextTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 65, -1));

        jBut_Ingresar.setText("Ingresar Datos");
        jBut_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 77, -1, -1));

        jBut_Limpiar.setText("Limpiar");
        jBut_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 77, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Ingrese Los Datos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jTextAreaDatos.setColumns(20);
        jTextAreaDatos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 11, 225, 89));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Metodos de Ordenamiento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jBut_Merge.setText("Merge");
        jBut_Merge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MergeActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Merge, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, -1, -1));

        jBut_Inserccion.setText("Inserccion");
        jBut_Inserccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InserccionActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Inserccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 177, -1, -1));

        jTextArea_Inserccion.setColumns(20);
        jTextArea_Inserccion.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Inserccion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 218, 218, 58));

        jTextArea_Merge.setColumns(20);
        jTextArea_Merge.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Merge);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 218, 208, 58));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodos de Busqueda");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jBUt_Secuencial.setText("Secuencial");
        jBUt_Secuencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUt_SecuencialActionPerformed(evt);
            }
        });
        getContentPane().add(jBUt_Secuencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 333, -1, -1));

        jBut_BInaria.setText("Binaria");
        jBut_BInaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_BInariaActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_BInaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 333, -1, -1));

        jTextArea_Binaria.setColumns(20);
        jTextArea_Binaria.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Binaria);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 362, 221, 59));

        jTextArea_secuencia.setColumns(20);
        jTextArea_secuencia.setRows(5);
        jScrollPane5.setViewportView(jTextArea_secuencia);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 362, 205, 59));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Todo Vector su primera posicion es \"0\".");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jBUt_eregresar.setText("Regresar");
        jBUt_eregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUt_eregresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBUt_eregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 447, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Form_BO.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 490));

        jMenu1.setText("Archivo");

        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String Abrir(File archivo){
        String Documento = "";
        try{
            entrada = new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter = (char)ascci;
                Documento+=caracter;
                
                
            }
            
        }catch (Exception e){     
        }
        return Documento;
    }
    
    public String Guardar(File archivo, String Documento){
        String mensaje = "";
        try{
            Salida = new FileOutputStream(archivo);
            byte[] bytxt = Documento.getBytes();
            Salida.write(bytxt);
            mensaje = "Archivo Guardado!!";
            
        }catch (Exception e){
        }
        return mensaje;
    }
    
    private void jBut_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_IngresarActionPerformed
        // TODO add your handling code here:
        if(jTextTamaño.getText().length()>0)
        {
            
            Ordenamientos OIngreso = new Ordenamientos();
            
            
            int Longitud_Vector = Integer.parseInt(jTextTamaño.getText());
            OIngreso.setLongitud(Longitud_Vector);
            OIngreso.InicializadorVector();
            
            for(int i=0; i < OIngreso.Longitud; i++)
            {
                String dato = JOptionPane.showInputDialog("Ingrese el dato para la posicion[ " + i + " ] del vector");
                if(!OIngreso.esNumero(dato)){
                    JOptionPane.showMessageDialog(this, "El Valor no es numerico, intente de nuevo");
                    this.jBut_LimpiarActionPerformed(evt);
                    return;
                    
                }
                OIngreso.Insertar(i, Integer.valueOf(dato));
            }
            jTextAreaDatos.setText(OIngreso.imprimir());
            this.OPrincipal = new Ordenamientos(Longitud_Vector);
            this.OPrincipal.setArreglo(OIngreso.getArreglo());
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debe de ingresar el tamaño del vector");
        }
    }//GEN-LAST:event_jBut_IngresarActionPerformed

    private void jBut_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_LimpiarActionPerformed
        // TODO add your handling code here:
        this.jTextAreaDatos.setText("");
        this.jTextArea_Inserccion.setText("");
        this.jTextArea_Merge.setText("");
        this.jTextTamaño.setText("");
        this.jTextArea_Binaria.setText("");
        this.jTextArea_secuencia.setText("");
        
    }//GEN-LAST:event_jBut_LimpiarActionPerformed

    private void jBut_MergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MergeActionPerformed
        // TODO add your handling code here:
        if(this.OPrincipal==null){
            JOptionPane.showMessageDialog(this, "Antes de ordenar debe de ingresar \n un vector con sus datos");
        }
        else
        {
            this.OPrincipal.MergeSort(OPrincipal.getArreglo());
            jTextArea_Merge.setText(this.OPrincipal.imprimir());
        }
    }//GEN-LAST:event_jBut_MergeActionPerformed

    private void jBut_InserccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InserccionActionPerformed
        // TODO add your handling code here:
         if(this.OPrincipal==null){
            JOptionPane.showMessageDialog(this, "Antes de ordenar debe de ingresar \n un vector con sus datos");
        }
         else{
             int[] vector_ordenado = this.OPrincipal.Inserccion(OPrincipal.getArreglo(), 0, OPrincipal.Longitud-1);
            jTextArea_Inserccion.setText(this.OPrincipal.Imprimir(vector_ordenado));
//             int[] vector_Ordenado = this.OPrincipal.Inserccion(vector)
         }
    }//GEN-LAST:event_jBut_InserccionActionPerformed

    private void jBUt_SecuencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUt_SecuencialActionPerformed
        // TODO add your handling code here:
         if(this.OPrincipal==null){
            JOptionPane.showMessageDialog(this, "Antes de ordenar debe de ingresar \n un vector con sus datos");
        }
         else{
             int dato =Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dato a buscar: "));
             jTextArea_secuencia.setText(this.OPrincipal.Secuencial(dato));
         }
    }//GEN-LAST:event_jBUt_SecuencialActionPerformed

    private void jBut_BInariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_BInariaActionPerformed
        // TODO add your handling code here:
         if(this.OPrincipal==null){
            JOptionPane.showMessageDialog(this, "Antes de ordenar debe de ingresar \n un vector con sus datos");
        }
         else
         {
             int dato =Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dato a buscar: "));
             int[] vector_Ordenado = this.OPrincipal.Inserccion(OPrincipal.getArreglo(), 0, OPrincipal.Longitud-1);
             
             int pos = this.OPrincipal.busquedaBinaria(vector_Ordenado, dato);
             
             if(pos==-1){
                 jTextArea_Binaria.setText("No se encontro el dato: "+ dato + " en el vector.");
             }
             else{
                  jTextArea_Binaria.setText(this.OPrincipal.Imprimir(vector_Ordenado) + "\n" + "posicion: "+ pos );
             }
         }
    }//GEN-LAST:event_jBut_BInariaActionPerformed

    private void jBUt_eregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUt_eregresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_jBUt_eregresarActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        // TODO add your handling code here:
        this.jTextAreaDatos.setText("");
        this.jTextArea_Inserccion.setText("");
        this.jTextArea_Merge.setText("");
        this.jTextTamaño.setText("");
        this.jTextArea_Binaria.setText("");
        this.jTextArea_secuencia.setText("");
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
       if(Seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
           archivo = Seleccionar.getSelectedFile();
           if(archivo.canRead()){
               if(archivo.getName().endsWith("txt")){
                   String documento = Abrir(archivo);
                     this.jTextAreaDatos.setText(documento);
                     this.jTextArea_Inserccion.setText(documento);
                     this.jTextArea_Merge.setText(documento);
                     this.jTextTamaño.setText(documento);
        
               }else{
                   JOptionPane.showMessageDialog(null, "Archivo Incomaptiible");
               }
           }
       }

    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
    JOptionPane.showMessageDialog(null, "Recuerda poner .txt al final ;)");
        if(Seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=Seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Documento = this.jTextAreaDatos.getText();
                String Mensaje = Guardar(archivo, Documento);
                if(Mensaje!= null){
                JOptionPane.showMessageDialog(null, Mensaje);
            }
                else
                {
                   JOptionPane.showMessageDialog(null, "Archivo No compatible"); 
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Guardad Documento de Texto");
            }
        }

    }//GEN-LAST:event_jMenuGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_BusquedaOrdenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_BusquedaOrdenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_BusquedaOrdenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_BusquedaOrdenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBUt_Secuencial;
    private javax.swing.JButton jBUt_eregresar;
    private javax.swing.JButton jBut_BInaria;
    private javax.swing.JButton jBut_Ingresar;
    private javax.swing.JButton jBut_Inserccion;
    private javax.swing.JButton jBut_Limpiar;
    private javax.swing.JButton jBut_Merge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaDatos;
    private javax.swing.JTextArea jTextArea_Binaria;
    private javax.swing.JTextArea jTextArea_Inserccion;
    private javax.swing.JTextArea jTextArea_Merge;
    private javax.swing.JTextArea jTextArea_secuencia;
    private javax.swing.JTextField jTextTamaño;
    // End of variables declaration//GEN-END:variables
}
