/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Automovil;
import Clases.Proyecto_ListaEnlazada;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class Form_Listas_Enlazadas extends javax.swing.JFrame {
    private Automovil objAuto;
    private Proyecto_ListaEnlazada objLE;
    Form_Menu Principal;
    
    /**
     * Creates new form Form_Listas_Enlazadas
     */
    public Form_Listas_Enlazadas(Form_Menu P) {
        initComponents();
        JOptionPane.showMessageDialog(null, "Notas:"
                + "\n  1: Para utilizar el metodo 1, crear la cola primero, posteriormente en el frame de Listas Enlazadas "
                + "\n  pulsar el boton crear y luego el boton de Metodo 1 'Traer Cola'"
                + "\n  2: El boton del metodo 2 'Cambiar posicion seleccionada a posicion 1'"
                + " solo funciona con datos creados en el Frame Lista Enlazada");
        Principal = P;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBUT_Crear = new javax.swing.JButton();
        JBUT_Aleatorio = new javax.swing.JButton();
        JBUT_InsInicio = new javax.swing.JButton();
        JBUT_InsFin = new javax.swing.JButton();
        JBUT_ElimInicio = new javax.swing.JButton();
        JBUT_ElimFinal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Aleatorios = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ListaEnlazada = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextPos = new javax.swing.JTextField();
        JBUT_PosxPosInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBUT_Cola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBUT_Crear.setText("Crear");
        JBUT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_CrearActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        JBUT_Aleatorio.setText("Aleatorio");
        JBUT_Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_AleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Aleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        JBUT_InsInicio.setText("Insertar Inicio");
        JBUT_InsInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_InsInicioActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_InsInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        JBUT_InsFin.setText("Insertar Final");
        JBUT_InsFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_InsFinActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_InsFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        JBUT_ElimInicio.setText("Eliminar Inicio");
        JBUT_ElimInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ElimInicioActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_ElimInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        JBUT_ElimFinal.setText("Eliminar Final");
        JBUT_ElimFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ElimFinalActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_ElimFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        jTable_Aleatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "PLACA", "MARCA", "MODELO", "COLOR", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Aleatorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, 50));

        jTable_ListaEnlazada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_ListaEnlazada.setTableHeader(null);
        jScrollPane2.setViewportView(jTable_ListaEnlazada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 270));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jTextPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, 20));

        JBUT_PosxPosInicio.setText("PosXxPosInicio");
        JBUT_PosxPosInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PosxPosInicioActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_PosxPosInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, -1));

        jLabel2.setText("Pos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        JBUT_Cola.setText("Metodo 1 \"Traer Cola\"");
        JBUT_Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ColaActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Fondo_LE.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBUT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_CrearActionPerformed
        // TODO add your handling code here:
        objLE = new Proyecto_ListaEnlazada();
    }//GEN-LAST:event_JBUT_CrearActionPerformed

    private void JBUT_AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_AleatorioActionPerformed
        // TODO add your handling code here:
        objAuto = new Automovil();
        objAuto.aleatorio(jTable_Aleatorios);
    }//GEN-LAST:event_JBUT_AleatorioActionPerformed

    private void JBUT_InsInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_InsInicioActionPerformed
        // TODO add your handling code here:
        String placa=this.jTable_Aleatorios.getValueAt(0, 0).toString();
        String marca=this.jTable_Aleatorios.getValueAt(0, 1).toString();
        int modelo= Integer.parseInt(this.jTable_Aleatorios.getValueAt(0,2).toString());
        String color= this.jTable_Aleatorios.getValueAt(0, 3).toString();
        double precio= Double.parseDouble(this.jTable_Aleatorios.getValueAt(0,4).toString());

        objAuto = new Automovil(placa, marca, modelo, color, precio);
        objLE.InsInicio(objAuto);
        objLE.MostrarLE(jTable_ListaEnlazada);
    }//GEN-LAST:event_JBUT_InsInicioActionPerformed

    private void JBUT_InsFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_InsFinActionPerformed
        // TODO add your handling code here:
        String Placa=this.jTable_Aleatorios.getValueAt(0, 0).toString();
        String Marca=this.jTable_Aleatorios.getValueAt(0, 1).toString();
        int Modelo= Integer.parseInt(this.jTable_Aleatorios.getValueAt(0,2).toString());
        String Color= this.jTable_Aleatorios.getValueAt(0, 3).toString();
        double Precio= Double.parseDouble(this.jTable_Aleatorios.getValueAt(0,4).toString());

        objAuto = new Automovil(Placa, Marca, Modelo, Color, Precio);
        objLE.InsFin(objAuto);
        objLE.MostrarLE(jTable_ListaEnlazada);
    }//GEN-LAST:event_JBUT_InsFinActionPerformed

    private void JBUT_ElimInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ElimInicioActionPerformed
        // TODO add your handling code here:
        objLE.ElimIni();
        objLE.MostrarLE(jTable_ListaEnlazada);
    }//GEN-LAST:event_JBUT_ElimInicioActionPerformed

    private void JBUT_ElimFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ElimFinalActionPerformed
        // TODO add your handling code here:
        objLE.ElimFin();
        objLE.MostrarLE(jTable_ListaEnlazada);
    }//GEN-LAST:event_JBUT_ElimFinalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPosActionPerformed

    private void JBUT_PosxPosInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PosxPosInicioActionPerformed
        // TODO add your handling code here:
         int posicion = Integer.parseInt(this.jTextPos.getText());
         objLE.PosxPrimerPos(posicion);
         objLE.MostrarLE(this.jTable_ListaEnlazada);
    }//GEN-LAST:event_JBUT_PosxPosInicioActionPerformed

    private void JBUT_ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ColaActionPerformed
        // TODO add your handling code here:
            int Traer = Integer.parseInt(Form_Cola.JTF_Dimension.getText().toString());
            for(int i=0; i<Traer; i++){
            String PlacaCola = Form_Cola.jTable_Colas.getValueAt(0, i).toString();
            String MarcaCola = Form_Cola.jTable_Colas.getValueAt(1, i).toString();
            int ModeloCola = Integer.parseInt(Form_Cola.jTable_Colas.getValueAt(2, i).toString());
            String ColorCola = Form_Cola.jTable_Colas.getValueAt(3, i).toString();
            double PrecioCola = Integer.parseInt(Form_Cola.jTable_Colas.getValueAt(2, i).toString());
            
            objAuto = new Automovil(PlacaCola, MarcaCola, ModeloCola, ColorCola, PrecioCola);
            objLE.InsFin(objAuto);
            objLE.MostrarLE(this.jTable_ListaEnlazada);
        }
    }//GEN-LAST:event_JBUT_ColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Listas_Enlazadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Listas_Enlazadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Listas_Enlazadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Listas_Enlazadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_Aleatorio;
    private javax.swing.JButton JBUT_Cola;
    private javax.swing.JButton JBUT_Crear;
    private javax.swing.JButton JBUT_ElimFinal;
    private javax.swing.JButton JBUT_ElimInicio;
    private javax.swing.JButton JBUT_InsFin;
    private javax.swing.JButton JBUT_InsInicio;
    private javax.swing.JButton JBUT_PosxPosInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Aleatorios;
    private javax.swing.JTable jTable_ListaEnlazada;
    private javax.swing.JTextField jTextPos;
    // End of variables declaration//GEN-END:variables
}
