/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Automovil;
import Clases.Proyecto_Pila;

/**
 *
 * @author adria
 */
public class Form_Pila extends javax.swing.JFrame {
      private Automovil objAuto;
      private Proyecto_Pila objPila;
    /**
     * Creates new form Form_Pila
     */
    Form_Menu principal;
    public Form_Pila(Form_Menu p) {
        initComponents();
        this.setLocationRelativeTo(null);
        principal = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JBUT_EliminarInvertir = new javax.swing.JButton();
        JBUT_ParImpar = new javax.swing.JButton();
        JBUT_Push = new javax.swing.JButton();
        JBUT_Aleatorio = new javax.swing.JButton();
        JBUT_Crear = new javax.swing.JButton();
        JTF_Dimension = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JBUT_Regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAleatorios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePilas = new javax.swing.JTable();
        JBUT_Pop = new javax.swing.JButton();
        JTF_Modelo = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Color", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBUT_EliminarInvertir.setText("EliminarInsertar");
        JBUT_EliminarInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_EliminarInvertirActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_EliminarInvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        JBUT_ParImpar.setText("PAR,IMPAR");
        JBUT_ParImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ParImparActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_ParImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        JBUT_Push.setText("PUSH");
        JBUT_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PushActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Push, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        JBUT_Aleatorio.setText("ALEATORIO");
        JBUT_Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_AleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Aleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        JBUT_Crear.setText("CREAR");
        JBUT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_CrearActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        getContentPane().add(JTF_Dimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 40, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIMENSION: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        JBUT_Regresar.setText("Regresar");
        JBUT_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        jTableAleatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Color", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAleatorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, 50));

        jTablePilas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Color", "Precio"
            }
        ));
        jScrollPane3.setViewportView(jTablePilas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 270));

        JBUT_Pop.setText("POP");
        JBUT_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PopActionPerformed(evt);
            }
        });
        getContentPane().add(JBUT_Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        JTF_Modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Fondo_Pila.png"))); // NOI18N
        JTF_Modelo.setOpaque(true);
        getContentPane().add(JTF_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 766, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBUT_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_JBUT_RegresarActionPerformed

    private void JBUT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_CrearActionPerformed
        // TODO add your handling code here:
        objPila = new Proyecto_Pila(Integer.parseInt(this.JTF_Dimension.getText()));
    }//GEN-LAST:event_JBUT_CrearActionPerformed

    private void JBUT_AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_AleatorioActionPerformed
        // TODO add your handling code here:
        objAuto= new Automovil();
        objAuto.aleatorio(jTableAleatorios);
        
    }//GEN-LAST:event_JBUT_AleatorioActionPerformed

    private void JBUT_PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PushActionPerformed
        // TODO add your handling code here:
       String Placa=this.jTableAleatorios.getValueAt(0, 0).toString();
       String Marca=this.jTableAleatorios.getValueAt(0, 1).toString();
       int Modelo= Integer.parseInt(this.jTableAleatorios.getValueAt(0,2).toString());
       String Color= this.jTableAleatorios.getValueAt(0, 3).toString();
       double Precio= Double.parseDouble(this.jTableAleatorios.getValueAt(0,4).toString());
        
       objAuto = new Automovil(Placa, Marca, Modelo, Color, Precio);
       objPila.push(objAuto);
       objPila.MostrarPila(jTablePilas);
      
    }//GEN-LAST:event_JBUT_PushActionPerformed

    private void JBUT_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PopActionPerformed
        // TODO add your handling code here:
        objPila.pop();
        objPila.MostrarPila(jTablePilas);
      
    }//GEN-LAST:event_JBUT_PopActionPerformed

    private void JBUT_ParImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ParImparActionPerformed
        // TODO add your handling code here:
        objPila.ParImpar();
        objPila.MostrarPila(jTablePilas);
    }//GEN-LAST:event_JBUT_ParImparActionPerformed

    private void JBUT_EliminarInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_EliminarInvertirActionPerformed
        // TODO add your handling code here:
        objPila.ELiminarInsertar();
        objPila.MostrarPila(jTablePilas);
    }//GEN-LAST:event_JBUT_EliminarInvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_Aleatorio;
    private javax.swing.JButton JBUT_Crear;
    private javax.swing.JButton JBUT_EliminarInvertir;
    private javax.swing.JButton JBUT_ParImpar;
    private javax.swing.JButton JBUT_Pop;
    private javax.swing.JButton JBUT_Push;
    private javax.swing.JButton JBUT_Regresar;
    private javax.swing.JTextField JTF_Dimension;
    private javax.swing.JLabel JTF_Modelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableAleatorios;
    private javax.swing.JTable jTablePilas;
    // End of variables declaration//GEN-END:variables
}
