/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.Recursividad;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class Form_P1T5 extends javax.swing.JFrame {
    Recursividad objRecur = new Recursividad();
    

    /**
     * Creates new form Form_P1T5
     */
    public Form_P1T5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTF_Numero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTF_CantIni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_TasaInt = new javax.swing.JTextField();
        jBut_Factorial = new javax.swing.JButton();
        jLab_Factorial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLab_FactorialRec = new javax.swing.JLabel();
        jLab_InversionRec = new javax.swing.JLabel();
        jLab_MultRusaRec = new javax.swing.JLabel();
        jLab_MaxCDRec = new javax.swing.JLabel();
        jLab_serieFibRec = new javax.swing.JLabel();
        jLab_ExpRec = new javax.swing.JLabel();
        jLab_sumVectorRec = new javax.swing.JLabel();
        jLab_sumVector = new javax.swing.JLabel();
        jLab_Exp = new javax.swing.JLabel();
        jLab_serieFib = new javax.swing.JLabel();
        jLab_MaxCD = new javax.swing.JLabel();
        jLab_MultRusa = new javax.swing.JLabel();
        jLab_Inversion = new javax.swing.JLabel();
        jBut_Inversion = new javax.swing.JButton();
        jTF_Años = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTF_Multiplicador = new javax.swing.JTextField();
        jTF_Multiplicando = new javax.swing.JTextField();
        jBut_MultRusa = new javax.swing.JButton();
        jTF_Numero1 = new javax.swing.JTextField();
        jTF_Numero2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBut_SerieFib = new javax.swing.JButton();
        jBut_MCD = new javax.swing.JButton();
        jTF_NumeroReal = new javax.swing.JTextField();
        jTF_NumeroFib = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTF_Potencia = new javax.swing.JTextField();
        jBut_expresion = new javax.swing.JButton();
        jTF_Numero1ParAmigo = new javax.swing.JTextField();
        jTF_Numero2ParAmigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jB_parAmigo = new javax.swing.JButton();
        jButton_sumaVector = new javax.swing.JButton();
        jButton_SumaMatrices = new javax.swing.JButton();
        jB_sumVector = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_M1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_M2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_SUMA = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setText("NÚMERO:");

        jTF_CantIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CantIniActionPerformed(evt);
            }
        });

        jLabel4.setText("CANT INI:");

        jLabel5.setText("TASA INT:");

        jBut_Factorial.setText("FACTORIAL");
        jBut_Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_FactorialActionPerformed(evt);
            }
        });

        jLab_Factorial.setBackground(new java.awt.Color(255, 51, 51));
        jLab_Factorial.setOpaque(true);

        jLabel2.setText("ITERATIVA");

        jLabel3.setText("RECURSIVA");

        jLab_FactorialRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_FactorialRec.setOpaque(true);

        jLab_InversionRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_InversionRec.setOpaque(true);

        jLab_MultRusaRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_MultRusaRec.setOpaque(true);

        jLab_MaxCDRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_MaxCDRec.setOpaque(true);

        jLab_serieFibRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_serieFibRec.setOpaque(true);

        jLab_ExpRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_ExpRec.setOpaque(true);

        jLab_sumVectorRec.setBackground(new java.awt.Color(255, 51, 51));
        jLab_sumVectorRec.setOpaque(true);

        jLab_sumVector.setBackground(new java.awt.Color(255, 51, 51));
        jLab_sumVector.setOpaque(true);

        jLab_Exp.setBackground(new java.awt.Color(255, 51, 51));
        jLab_Exp.setOpaque(true);

        jLab_serieFib.setBackground(new java.awt.Color(255, 51, 51));
        jLab_serieFib.setOpaque(true);

        jLab_MaxCD.setBackground(new java.awt.Color(255, 51, 51));
        jLab_MaxCD.setOpaque(true);

        jLab_MultRusa.setBackground(new java.awt.Color(255, 51, 51));
        jLab_MultRusa.setOpaque(true);

        jLab_Inversion.setBackground(new java.awt.Color(255, 51, 51));
        jLab_Inversion.setOpaque(true);

        jBut_Inversion.setText("INVERSION");
        jBut_Inversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_InversionActionPerformed(evt);
            }
        });

        jTF_Años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_AñosActionPerformed(evt);
            }
        });

        jLabel6.setText("AÑOS:");

        jLabel7.setText("MULTIPLICADOR:");

        jLabel8.setText("MULTIPLICANDO:");

        jTF_Multiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_MultiplicadorActionPerformed(evt);
            }
        });

        jTF_Multiplicando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_MultiplicandoActionPerformed(evt);
            }
        });

        jBut_MultRusa.setText("Mult Rusa");
        jBut_MultRusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MultRusaActionPerformed(evt);
            }
        });

        jTF_Numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Numero1ActionPerformed(evt);
            }
        });

        jTF_Numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Numero2ActionPerformed(evt);
            }
        });

        jLabel9.setText("NUMERO 2:");

        jLabel10.setText("NUMERO 1:");

        jBut_SerieFib.setText("SerieFib");
        jBut_SerieFib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SerieFibActionPerformed(evt);
            }
        });

        jBut_MCD.setText("MaxCD");
        jBut_MCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_MCDActionPerformed(evt);
            }
        });

        jTF_NumeroReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NumeroRealActionPerformed(evt);
            }
        });

        jTF_NumeroFib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NumeroFibActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO:");

        jLabel12.setText("NÚMERO REAL:");

        jLabel13.setText("POTENCIA:");

        jTF_Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_PotenciaActionPerformed(evt);
            }
        });

        jBut_expresion.setText("Expresion");
        jBut_expresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_expresionActionPerformed(evt);
            }
        });

        jTF_Numero1ParAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Numero1ParAmigoActionPerformed(evt);
            }
        });

        jTF_Numero2ParAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Numero2ParAmigoActionPerformed(evt);
            }
        });

        jLabel14.setText("NUMERO 2:");

        jLabel15.setText("NUMERO 1:");

        jB_parAmigo.setText("Par Amigo");
        jB_parAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_parAmigoActionPerformed(evt);
            }
        });

        jButton_sumaVector.setText("Suma Vector");
        jButton_sumaVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sumaVectorActionPerformed(evt);
            }
        });

        jButton_SumaMatrices.setText("Suma Matrices");
        jButton_SumaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SumaMatricesActionPerformed(evt);
            }
        });

        jB_sumVector.setText("Suma Vector");
        jB_sumVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sumVectorActionPerformed(evt);
            }
        });

        jTable_M1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable_M1);

        jTable_M2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jTable_M2);

        jTable_SUMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(jTable_SUMA);

        jLabel16.setText("Matriz 1:");

        jLabel17.setText("Matriz 2:");

        jLabel18.setText("Suma:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_Multiplicando, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_Multiplicador))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(38, 38, 38)
                                .addComponent(jTF_Numero1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Potencia)
                                    .addComponent(jTF_NumeroReal)
                                    .addComponent(jTF_NumeroFib)
                                    .addComponent(jTF_Numero2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Numero)
                                    .addComponent(jTF_CantIni)
                                    .addComponent(jTF_Años)
                                    .addComponent(jTF_TasaInt)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_Numero1ParAmigo)
                                    .addComponent(jTF_Numero2ParAmigo))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBut_Factorial)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jBut_MultRusa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBut_Inversion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBut_MCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBut_SerieFib, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBut_expresion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(140, 140, 140)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(128, 128, 128)
                                            .addComponent(jLabel3)
                                            .addGap(52, 52, 52))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLab_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLab_Inversion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLab_InversionRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLab_FactorialRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLab_MultRusaRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLab_MultRusa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLab_MaxCD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLab_serieFib, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLab_serieFibRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(191, 191, 191)
                                            .addComponent(jLab_MaxCDRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLab_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLab_ExpRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLab_sumVector, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLab_sumVectorRec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jB_sumVector, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_sumaVector, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_parAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_SumaMatrices))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLab_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTF_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBut_Factorial))
                    .addComponent(jLab_FactorialRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTF_CantIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTF_TasaInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jBut_Inversion))))
                    .addComponent(jLab_Inversion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_InversionRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTF_Multiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTF_Multiplicando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBut_MultRusa))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLab_MultRusa, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLab_MultRusaRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTF_Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBut_MCD))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLab_MaxCD, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLab_MaxCDRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTF_NumeroFib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBut_SerieFib))
                    .addComponent(jLab_serieFib, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_serieFibRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTF_NumeroReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTF_Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBut_expresion))
                    .addComponent(jLab_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_ExpRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_sumVector)
                    .addComponent(jLab_sumVector, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLab_sumVectorRec, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Numero1ParAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTF_Numero2ParAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jB_parAmigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sumaVector)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_SumaMatrices))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_FactorialActionPerformed
        double res = objRecur.Factorial(Integer.parseInt(this.jTF_Numero.getText()));
        this.jLab_Factorial.setText(""+res);       

        res = objRecur.FactorialRec2(Integer.parseInt(this.jTF_Numero.getText()));
        this.jLab_FactorialRec.setText(""+res);
        
    }//GEN-LAST:event_jBut_FactorialActionPerformed

    private void jTF_CantIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CantIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_CantIniActionPerformed

    private void jTF_AñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_AñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_AñosActionPerformed

    private void jBut_InversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_InversionActionPerformed
        double cantIni = Double.parseDouble(this.jTF_CantIni.getText());
        int tasa = Integer.parseInt(this.jTF_TasaInt.getText());
        int años = Integer.parseInt(this.jTF_Años.getText());
        
        this.jLab_Inversion.setText(objRecur.Inversion(cantIni, tasa, años)+"");
        this.jLab_InversionRec.setText(objRecur.InversionRec(cantIni, tasa, años)+"");
    }//GEN-LAST:event_jBut_InversionActionPerformed

    private void jTF_MultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_MultiplicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_MultiplicadorActionPerformed

    private void jTF_MultiplicandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_MultiplicandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_MultiplicandoActionPerformed

    private void jBut_MultRusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MultRusaActionPerformed
        int multiplicador = Integer.parseInt(this.jTF_Multiplicador.getText());
        int multiplicando = Integer.parseInt(this.jTF_Multiplicando.getText());
        if(multiplicando > multiplicador){
            
            int aux = multiplicando;
            multiplicando = multiplicador;
            multiplicador = aux;
        }
        
        this.jLab_MultRusa.setText(objRecur.MultiplicRusa(multiplicador, multiplicando) +"");
        this.jLab_MultRusaRec.setText(objRecur.MultipliRusaRec(multiplicador, multiplicando, 0) +"");
    }//GEN-LAST:event_jBut_MultRusaActionPerformed

    private void jTF_Numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Numero1ActionPerformed

    private void jTF_Numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Numero2ActionPerformed

    private void jBut_MCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_MCDActionPerformed
        int Dividendo = Integer.parseInt(this.jTF_Numero1.getText());
        int Divisor = Integer.parseInt(this.jTF_Numero2.getText());
        if(Divisor > Dividendo){
            int aux = Divisor;
            Divisor = Dividendo;
            Dividendo = aux;
        }
        
        this.jLab_MaxCD.setText(objRecur.MaxCD(Dividendo, Divisor)+"");
        this.jLab_MaxCDRec.setText(objRecur.MaxCDRec(Dividendo, Divisor)+"");
    }//GEN-LAST:event_jBut_MCDActionPerformed

    private void jTF_NumeroFibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NumeroFibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NumeroFibActionPerformed

    private void jBut_SerieFibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SerieFibActionPerformed
        int elemento = Integer.parseInt(this.jTF_NumeroFib.getText());
        this.jLab_serieFib.setText(objRecur.serieFib(elemento)+"");
        this.jLab_serieFibRec.setText(objRecur.serieFibRec(0, 1, "0,1", Integer.parseInt(this.jTF_NumeroFib.getText())));
    }//GEN-LAST:event_jBut_SerieFibActionPerformed

    private void jTF_NumeroRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NumeroRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NumeroRealActionPerformed

    private void jTF_PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_PotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_PotenciaActionPerformed

    private void jBut_expresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_expresionActionPerformed
        double num = Double.parseDouble(this.jTF_NumeroReal.getText());
        int pot = Integer.parseInt(this.jTF_Potencia.getText());
        this.jLab_Exp.setText(objRecur.expPot(num, pot)+"");
        this.jLab_ExpRec.setText(objRecur.ExpPotRec(num, pot, 1)+"");
    }//GEN-LAST:event_jBut_expresionActionPerformed

    private void jB_sumVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sumVectorActionPerformed
        int []arrInt = new int[10]; Random rnd = new Random();
        for (int i = 0; i < arrInt.length; i++)
            arrInt[i] = rnd.nextInt(11);
        
    }//GEN-LAST:event_jB_sumVectorActionPerformed

    private void jTF_Numero2ParAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Numero2ParAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Numero2ParAmigoActionPerformed

    private void jTF_Numero1ParAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Numero1ParAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Numero1ParAmigoActionPerformed

    private void jB_parAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_parAmigoActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(this.jTF_Numero1ParAmigo.getText());
        int num2 = Integer.parseInt(this.jTF_Numero2ParAmigo.getText());
        boolean res;
        res = objRecur.ParAmigos(Integer.parseInt(this.jTF_Numero1.getText().toString()), Integer.parseInt(this.jTF_Numero2.getText().toString()));
        if(res)
            JOptionPane.showMessageDialog(null, "Los numeros son par amigo");
        else
            JOptionPane.showMessageDialog(null, "Los numeros no son par amigos");
        if(num1==objRecur.SumaParAmigoN2Rec(num2, 0, 1) && num2 == objRecur.SumaParAmigoN1Rec(num1, 0, 1)){
            JOptionPane.showMessageDialog(null,"Los numero son par amigo");
            
        }
        else
            JOptionPane.showMessageDialog(null,"Los numero no son par amigo");

    }//GEN-LAST:event_jB_parAmigoActionPerformed

    private void jButton_sumaVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sumaVectorActionPerformed
        int []arrInt = new int [10]; Random rnd = new Random();
        for (int i = 0; i <arrInt.length; i++) {
            arrInt[i]=rnd.nextInt(11);
        }
        this.jLab_sumVector.setText(objRecur.SumaVector(arrInt)+"");
        this.jLab_sumVectorRec.setText(objRecur.SumaVectorRec(arrInt, 0, 0)+"");
    }//GEN-LAST:event_jButton_sumaVectorActionPerformed

    private void jButton_SumaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SumaMatricesActionPerformed
        int [][]s1 = {{1,2,3},{1,2,3},{1,2,3},{1,2,3}};
        int [][]s2 = {{1,1,1},{2,2,2},{3,3,3},{4,4,4}};
        for (int r = 0; r <s1.length; r++) 
            for (int c = 0; c <s1[0].length; c++){ 
                this.jTable_M1.setValueAt(s1[r][c], r, c);
                this.jTable_M2.setValueAt(s2[r][c], r, c);
        }
        int [][]suma = new int [4][3];
        objRecur.SumaMatrices(s1, s2, suma);
        for (int r = 0; r < s1.length; r++) 
            for (int c = 0; c <s1[0].length; c++) {
                this.jTable_SUMA.setValueAt(suma[r][c], r, c);
        }
    }//GEN-LAST:event_jButton_SumaMatricesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_P1T5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_P1T5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_P1T5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_P1T5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_P1T5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_parAmigo;
    private javax.swing.JButton jB_sumVector;
    private javax.swing.JButton jBut_Factorial;
    private javax.swing.JButton jBut_Inversion;
    private javax.swing.JButton jBut_MCD;
    private javax.swing.JButton jBut_MultRusa;
    private javax.swing.JButton jBut_SerieFib;
    private javax.swing.JButton jBut_expresion;
    private javax.swing.JButton jButton_SumaMatrices;
    private javax.swing.JButton jButton_sumaVector;
    private javax.swing.JLabel jLab_Exp;
    private javax.swing.JLabel jLab_ExpRec;
    private javax.swing.JLabel jLab_Factorial;
    private javax.swing.JLabel jLab_FactorialRec;
    private javax.swing.JLabel jLab_Inversion;
    private javax.swing.JLabel jLab_InversionRec;
    private javax.swing.JLabel jLab_MaxCD;
    private javax.swing.JLabel jLab_MaxCDRec;
    private javax.swing.JLabel jLab_MultRusa;
    private javax.swing.JLabel jLab_MultRusaRec;
    private javax.swing.JLabel jLab_serieFib;
    private javax.swing.JLabel jLab_serieFibRec;
    private javax.swing.JLabel jLab_sumVector;
    private javax.swing.JLabel jLab_sumVectorRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF_Años;
    private javax.swing.JTextField jTF_CantIni;
    private javax.swing.JTextField jTF_Multiplicador;
    private javax.swing.JTextField jTF_Multiplicando;
    private javax.swing.JTextField jTF_Numero;
    private javax.swing.JTextField jTF_Numero1;
    private javax.swing.JTextField jTF_Numero1ParAmigo;
    private javax.swing.JTextField jTF_Numero2;
    private javax.swing.JTextField jTF_Numero2ParAmigo;
    private javax.swing.JTextField jTF_NumeroFib;
    private javax.swing.JTextField jTF_NumeroReal;
    private javax.swing.JTextField jTF_Potencia;
    private javax.swing.JTextField jTF_TasaInt;
    private javax.swing.JTable jTable_M1;
    private javax.swing.JTable jTable_M2;
    private javax.swing.JTable jTable_SUMA;
    // End of variables declaration//GEN-END:variables
}
