/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Clases.Cola;
import Clases.Proceso;

/**
 *
 * @author aa421
 */
public class Form_Colas extends javax.swing.JFrame {
Cola objCola;
Proceso objProc;
    /**
     * Proceso
     * Creates new form Form_Colas
     */
    public Form_Colas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Aleatorio1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Pila1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Aleatorio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cola = new javax.swing.JTable();
        jBUT_Crear = new javax.swing.JButton();
        jBUT_Aleatorios = new javax.swing.JButton();
        jBUT_Insertar = new javax.swing.JButton();
        jBUt_Eliminar = new javax.swing.JButton();
        JTF_Dimension = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBUT_Invertir = new javax.swing.JButton();
        JBUT_EliminarMedio = new javax.swing.JButton();
        JBUT_EliminarPos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jText_Posicion = new javax.swing.JTextField();
        JBUT_Pos1Pos2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTF_Pos1 = new javax.swing.JTextField();
        JTF_Pos2 = new javax.swing.JTextField();
        JBUT_MitadImPa = new javax.swing.JButton();
        JBUT_ParImpar = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Aleatorio1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Aleatorio1);

        jTable_Pila1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_Pila1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Aleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ));
        jScrollPane1.setViewportView(jTable_Aleatorio);
        if (jTable_Aleatorio.getColumnModel().getColumnCount() > 0) {
            jTable_Aleatorio.getColumnModel().getColumn(2).setResizable(false);
        }

        jTable_Cola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Cola.setTableHeader(null);
        jScrollPane2.setViewportView(jTable_Cola);

        jBUT_Crear.setText("Crear");
        jBUT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_CrearActionPerformed(evt);
            }
        });

        jBUT_Aleatorios.setText("Aleatorio");
        jBUT_Aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_AleatoriosActionPerformed(evt);
            }
        });

        jBUT_Insertar.setText("Insertar");
        jBUT_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_InsertarActionPerformed(evt);
            }
        });

        jBUt_Eliminar.setText("Eliminar");
        jBUt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUt_EliminarActionPerformed(evt);
            }
        });

        JTF_Dimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_DimensionActionPerformed(evt);
            }
        });

        jLabel1.setText("Dimension");

        jBUT_Invertir.setText("Invertir");
        jBUT_Invertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUT_InvertirActionPerformed(evt);
            }
        });

        JBUT_EliminarMedio.setText("EliminarM");
        JBUT_EliminarMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_EliminarMedioActionPerformed(evt);
            }
        });

        JBUT_EliminarPos.setText("EliminarPos");
        JBUT_EliminarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_EliminarPosActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion:");

        JBUT_Pos1Pos2.setText("Pos1xPos2");
        JBUT_Pos1Pos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_Pos1Pos2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Posicion 1:");

        jLabel4.setText("Posicion 2:");

        JBUT_MitadImPa.setText("ParxImpar");
        JBUT_MitadImPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_MitadImPaActionPerformed(evt);
            }
        });

        JBUT_ParImpar.setText("ParxImpar(2)");
        JBUT_ParImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ParImparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTF_Pos2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTF_Pos1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jText_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTF_Dimension)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBUT_Invertir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUT_EliminarMedio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUT_EliminarPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUT_Pos1Pos2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBUT_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBUT_Aleatorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBUT_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBUt_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBUT_MitadImPa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBUT_ParImpar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBUT_Crear)
                    .addComponent(jBUT_Aleatorios)
                    .addComponent(JTF_Dimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jBUT_Insertar)
                    .addComponent(jBUt_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBUT_Invertir)
                    .addComponent(JBUT_EliminarMedio)
                    .addComponent(JBUT_EliminarPos)
                    .addComponent(jLabel2)
                    .addComponent(jText_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUT_Pos1Pos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUT_MitadImPa)
                    .addComponent(JBUT_ParImpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTF_Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_DimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_DimensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_DimensionActionPerformed

    private void jBUT_AleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_AleatoriosActionPerformed
        // TODO add your handling code here:
        objProc = new Proceso();
        objProc.Aleatorio(jTable_Aleatorio);
        
    }//GEN-LAST:event_jBUT_AleatoriosActionPerformed

    private void jBUT_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_InsertarActionPerformed
        // TODO add your handling code here:
        int numProc = Integer.parseInt(this.jTable_Aleatorio.getValueAt(0,0).toString());
        String tipoProc =this.jTable_Aleatorio.getValueAt(0, 1).toString();
        double quantum = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0,2).toString());
        objProc = new Proceso(numProc, tipoProc, quantum);
        objCola.Insertar(objProc);
        objCola.Mostrar(jTable_Cola);
        
    }//GEN-LAST:event_jBUT_InsertarActionPerformed

    private void jBUt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUt_EliminarActionPerformed
        // TODO add your handling code here:
        objCola.eliminar();
        objCola.Mostrar(jTable_Cola);
    }//GEN-LAST:event_jBUt_EliminarActionPerformed

    private void jBUT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_CrearActionPerformed
        // TODO add your handling code here:
        objCola = new Cola(Integer.parseInt(this.JTF_Dimension.getText()));
    }//GEN-LAST:event_jBUT_CrearActionPerformed

    private void jBUT_InvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUT_InvertirActionPerformed
        // TODO add your handling code here:
        objCola.InvertirCola();
        objCola.Mostrar(jTable_Cola);
    }//GEN-LAST:event_jBUT_InvertirActionPerformed

    private void JBUT_EliminarMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_EliminarMedioActionPerformed
        // TODO add your handling code here:
        objCola.elimMedio();
        objCola.Mostrar(jTable_Cola);
    
    }//GEN-LAST:event_JBUT_EliminarMedioActionPerformed

    private void JBUT_EliminarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_EliminarPosActionPerformed
        // TODO add your handling code here:
        objCola.elimPos(Integer.parseInt(this.jText_Posicion.getText()));
        objCola.Mostrar(jTable_Cola);
        
    }//GEN-LAST:event_JBUT_EliminarPosActionPerformed

    private void JBUT_Pos1Pos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_Pos1Pos2ActionPerformed
        // TODO add your handling code here:
        int pos1 = Integer.parseInt(this.JTF_Pos1.getText());
        int pos2 = Integer.parseInt(this.JTF_Pos2.getText());
        
        objCola.intPos1xPos2(pos1, pos2);
        objCola.Mostrar(jTable_Cola);
    }//GEN-LAST:event_JBUT_Pos1Pos2ActionPerformed

    private void JBUT_MitadImPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_MitadImPaActionPerformed
        // TODO add your handling code here:
        objCola.intPosParxPosImp();
        objCola.Mostrar(jTable_Cola);
    }//GEN-LAST:event_JBUT_MitadImPaActionPerformed

    private void JBUT_ParImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ParImparActionPerformed
        // TODO add your handling code here:
        objCola.intPosParxPosImp2();
        objCola.Mostrar(jTable_Cola);
    }//GEN-LAST:event_JBUT_ParImparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_EliminarMedio;
    private javax.swing.JButton JBUT_EliminarPos;
    private javax.swing.JButton JBUT_MitadImPa;
    private javax.swing.JButton JBUT_ParImpar;
    private javax.swing.JButton JBUT_Pos1Pos2;
    private javax.swing.JTextField JTF_Dimension;
    private javax.swing.JTextField JTF_Pos1;
    private javax.swing.JTextField JTF_Pos2;
    private javax.swing.JButton jBUT_Aleatorios;
    private javax.swing.JButton jBUT_Crear;
    private javax.swing.JButton jBUT_Insertar;
    private javax.swing.JButton jBUT_Invertir;
    private javax.swing.JButton jBUt_Eliminar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Aleatorio;
    private javax.swing.JTable jTable_Aleatorio1;
    private javax.swing.JTable jTable_Cola;
    private javax.swing.JTable jTable_Pila1;
    private javax.swing.JTextField jText_Posicion;
    // End of variables declaration//GEN-END:variables
}
