/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Pila;
import Clases.Proceso;

/**
 *
 * @author aa421
 */
public class Form_pilas extends javax.swing.JFrame {
    private Proceso objProc;
    private Pila objPila;
    /**
     * Creates new form Form_pilas
     */
    public Form_pilas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTF_Dimension = new javax.swing.JTextField();
        JBUT_Crear = new javax.swing.JButton();
        JBUT_Aleatorios = new javax.swing.JButton();
        JBUT_Push = new javax.swing.JButton();
        JBUT_Pop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Aleatorio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Pila = new javax.swing.JTable();
        JBUT_pila = new javax.swing.JButton();
        JBUT_elimMedio = new javax.swing.JButton();
        JBUT_elimFondo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JBUT_Penultimo = new javax.swing.JButton();
        JBUT_Par = new javax.swing.JButton();
        JBUT_InvMitad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_Pos1 = new javax.swing.JTextField();
        JTF_Pos2 = new javax.swing.JTextField();
        JBUT_Cambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dimensión: ");

        JBUT_Crear.setText("Crear");
        JBUT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_CrearActionPerformed(evt);
            }
        });

        JBUT_Aleatorios.setText("Aleatorios");
        JBUT_Aleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_AleatoriosActionPerformed(evt);
            }
        });

        JBUT_Push.setText("Push");
        JBUT_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PushActionPerformed(evt);
            }
        });

        JBUT_Pop.setText("Pop");
        JBUT_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PopActionPerformed(evt);
            }
        });

        jTable_Aleatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Aleatorio);

        jTable_Pila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num.Proceso", "Tipo Proceso", "Quantum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Pila);

        JBUT_pila.setText("Invertir");
        JBUT_pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_pilaActionPerformed(evt);
            }
        });

        JBUT_elimMedio.setText("Eliminar medio");
        JBUT_elimMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_elimMedioActionPerformed(evt);
            }
        });

        JBUT_elimFondo.setText("Eliminar Elemnto Fondo");
        JBUT_elimFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_elimFondoActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar e invertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBUT_Penultimo.setText("Eliminar Pen.");
        JBUT_Penultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_PenultimoActionPerformed(evt);
            }
        });

        JBUT_Par.setText("Par");
        JBUT_Par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_ParActionPerformed(evt);
            }
        });

        JBUT_InvMitad.setText("InvertirMitad");
        JBUT_InvMitad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_InvMitadActionPerformed(evt);
            }
        });

        jLabel2.setText("Pos1");

        jLabel3.setText("Pos2");

        JBUT_Cambiar.setText("CambiarPos");
        JBUT_Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUT_CambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTF_Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTF_Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBUT_elimFondo)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBUT_Penultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JBUT_Par, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JBUT_InvMitad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JBUT_pila)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JBUT_Cambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JBUT_elimMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTF_Dimension, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBUT_Crear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUT_Aleatorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBUT_Push)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBUT_Pop))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTF_Dimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBUT_Crear)
                            .addComponent(JBUT_Aleatorios)
                            .addComponent(JBUT_Push)
                            .addComponent(JBUT_Pop))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(JBUT_InvMitad)
                            .addComponent(JBUT_Par)
                            .addComponent(jLabel2)
                            .addComponent(JTF_Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JBUT_elimMedio)
                                .addComponent(JBUT_pila))
                            .addComponent(JBUT_elimFondo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTF_Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBUT_Penultimo)
                    .addComponent(JBUT_Cambiar))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBUT_AleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_AleatoriosActionPerformed
        // TODO add your handling code here:
        objProc= new Proceso();
        objProc.Aleatorio(jTable_Aleatorio);
    }//GEN-LAST:event_JBUT_AleatoriosActionPerformed

    private void JBUT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_CrearActionPerformed
        // TODO add your handling code here:
        objPila = new Pila(Integer.parseInt(this.JTF_Dimension.getText()));
    }//GEN-LAST:event_JBUT_CrearActionPerformed

    private void JBUT_PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PushActionPerformed
        // TODO add your handling code here:
        int numProc = Integer.parseInt(this.jTable_Aleatorio.getValueAt(0,0).toString());
        String tipoProc =this.jTable_Aleatorio.getValueAt(0, 1).toString();
        double quantum = Double.parseDouble(this.jTable_Aleatorio.getValueAt(0,2).toString());
        objProc = new Proceso(numProc, tipoProc, quantum);
        objPila.push(objProc);
        objPila.MostrarPila(jTable_Pila);
        
    }//GEN-LAST:event_JBUT_PushActionPerformed

    private void JBUT_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PopActionPerformed
        // TODO add your handling code here:
        objPila.pop();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_PopActionPerformed

    private void JBUT_pilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_pilaActionPerformed
        // TODO add your handling code here:
        objPila.invertirPila();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_pilaActionPerformed

    private void JBUT_elimMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_elimMedioActionPerformed
        // TODO add your handling code here:
        objPila.elimMedio();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_elimMedioActionPerformed

    private void JBUT_elimFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_elimFondoActionPerformed
        // TODO add your handling code here:
    objPila.eliminElementoFondo();
    objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_elimFondoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        objPila.EliminarPilaMedio();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBUT_PenultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_PenultimoActionPerformed
        // TODO add your handling code here:
        objPila.CambiarPenultimo();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_PenultimoActionPerformed

    private void JBUT_ParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_ParActionPerformed
        // TODO add your handling code here:
        objPila.trenza();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_ParActionPerformed

    private void JBUT_InvMitadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_InvMitadActionPerformed
        // TODO add your handling code here:
        objPila.InvertirMitad();
        objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_InvMitadActionPerformed

    private void JBUT_CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUT_CambiarActionPerformed
        // TODO add your handling code here:
      objPila.InvertirMitades();
      objPila.MostrarPila(jTable_Pila);
    }//GEN-LAST:event_JBUT_CambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_pilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_pilas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUT_Aleatorios;
    private javax.swing.JButton JBUT_Cambiar;
    private javax.swing.JButton JBUT_Crear;
    private javax.swing.JButton JBUT_InvMitad;
    private javax.swing.JButton JBUT_Par;
    private javax.swing.JButton JBUT_Penultimo;
    private javax.swing.JButton JBUT_Pop;
    private javax.swing.JButton JBUT_Push;
    private javax.swing.JButton JBUT_elimFondo;
    private javax.swing.JButton JBUT_elimMedio;
    private javax.swing.JButton JBUT_pila;
    private javax.swing.JTextField JTF_Dimension;
    private javax.swing.JTextField JTF_Pos1;
    private javax.swing.JTextField JTF_Pos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Aleatorio;
    private javax.swing.JTable jTable_Pila;
    // End of variables declaration//GEN-END:variables
}
